<!--- begin footer --->

<div class="footer">
  <hr>
  <b><a href="http://www.becomeonewiththecode.com">www.becomeonewiththecode.com</a></b>
</div>

<!-- Google adds --->

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Becomeonewiththecode.com -->
  <ins class="adsbygoogle"
   style="display:block"
   data-ad-client="ca-pub-9703614120192799"
   data-ad-slot="2347233815"
   data-ad-format="auto">
  </ins>
   <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
<!-- End Google adds --->

<!-- start google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77271894-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- end google analytics -->

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>


<!--- end footer --->
