<!--- begin right column --->

<div class="col-md-2">

<!-- begin content -->
<div class="list-group">
    <a href="#" class="list-group-item active">
    <h4 class="list-group-item-heading">Version Control</h4>
      <p class="list-group-item-text">A system and process that keeps track of changes within a file giving you the ability to revert, recover and merge differencees very quickly and efficiently. Git is a well known open source VCS, VCM  application that accomplish this goal quite easily.
      </p>
    </a>
</div>

<div class="list-group">
  <a href="#" class="list-group-item active">
    GIT helper utilities
  </a>
  <a href="https://www.gitkraken.com/" class="list-group-item">GITKRAKEN - GIT client</a>
  <a href="https://www.kernel.org/pub/software/scm/git/docs/gitk.html" class="list-group-item">GITK - GIT browser</a>
  <a href="http://jonas.nitro.dk/tig/" class="list-group-item">TIG - text based interface to GIT</a>
  <a href="https://github.com/nojhan/liquidprompt" class="list-group-item">LiquidPrompt - Adaptive shell prompt</a>
</div>

<!--- end content --->

</div>

<!--- end right column --->
