<!--- begin lef column --->

  <div class="col-md-2">
    <div class="list-group">
        <a href="git.php" class="list-group-item">Git</a>
        <a href="ansible.php" class="list-group-item">Ansible</a>
        <a href="#" class="list-group-item disabled">Vagrant</a>
        <a href="docker.php" class="list-group-item">Docker</a>
        <a href="#" class="list-group-item disabled">BootStrap</a>
        <a href="#" class="list-group-item disabled">Python</a>
    </div>
  </div>

<!--- end left column --->
