<!--- begin navbar --->

<!--- begin Navigation header --->
<nav class="navbar navbar-inverse navbar-fixed-top">

  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Become one with the Code</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="index.html"><icon class="fa fa-home fa-fw fa-2x"></a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Articles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="git.html">GIT</a></li>
            <li><a href="index.html">Ansible</a></li>
            <li><a href="index.html">Docker</a></li>
          </ul>
        </li>
      </ul>
    </div>


  </div>
</nav>
<!--- end Navigation header --->


<!--- end navbar --->
