<!--- begin navbar --->

<!--- begin Navigation header --->
<nav class="navbar navbar-inverse navbar-fixed-top">

  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/index.php">Become one with the Code</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/index.php"><icon class="fa fa-home fa-fw fa-2x"></a></li>
        <li class="active"><a href="/about.php">About</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Articles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/git/git.php">GIT</a></li>
            <li><a href="/terraform/terraform.php">Terraform</a></li>
            <li><a href="/vagrant/vagrant.php">Vagrant</a></li>
          </ul>
        </li>
      </ul>
    </div>


  </div>
</nav>
<!--- end Navigation header --->
<!--- end navbar --->

<!--- begin google page level adds --->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-9703614120192799",
    enable_page_level_ads: true
  });
</script>
<!--- end google page level adds --->
