<!--- begin right column --->

<div class="col-md-2">

<!-- begin content -->
<div class="list-group">
    <a href="#" class="list-group-item active">
    <h4 class="list-group-item-heading">Version Control</h4>
      <p class="list-group-item-text">A system and process that keeps track of changes within a file giving you the ability to revert, recover and merge differencees very quickly and efficiently. Git is a well known open source VCS, VCM  application that accomplish this goal quite easily.
      </p>
    </a>
</div>
<!--- end content --->

</div>

<!--- end right column --->
